spring.application.name=ASNOT
server.port=8081
server.address=0.0.0.0


spring.datasource.url=jdbc:postgresql://localhost:5432/mydb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm
jwt.expiration=86400000

office.lat=-7.2381446
office.lon=108.3682641
# in meter
office.radius=10
# default
EARTH_RADIUS=6371000